name: flutter-engineer-codecheck-2024
packages:
  - packages/**
ignore:
  - "packages/mason"
sdkPath: .fvm/flutter_sdk

scripts:
  analyze:
    exec: dart analyze .
  test:
    run: melos exec  --dir-exists="test" -- fvm flutter test
  build_runner:
    run: melos exec  --depends-on="build_runner" -- fvm dart run build_runner build --delete-conflicting-outputs
  build_watch:
    run: melos exec  --depends-on="build_runner" -- fvm dart run build_runner watch --delete-conflicting-outputs
  gen-l10n:
    run: melos exec  --depends-on="intl" --  fvm flutter gen-l10n  --no-nullable-getter  --no-synthetic-package --arb-dir l10n --output-dir ./lib/gen_l10n   --untranslated-messages-file l10n_missing_keywords.txt

  run_dummy:
    run: melos exec  --file-exists="lib/app.dart" --  fvm flutter run --flavor=dev -t execute_with_dummy/main_with_dummy.dart
  run_slow:
    run: melos exec  --file-exists="lib/app.dart" --  fvm flutter run --flavor=dev -t execute_with_dummy/main_with_slow.dart
  run_dev:
    run: melos exec  --file-exists="lib/app.dart" --  fvm flutter run --flavor=dev -t lib/main_dev.dart
  run_prod:
    run: melos exec  --file-exists="lib/app.dart" --  fvm flutter run --flavor=prod -t lib/main_prod.dart

  init:
    run: melos bs && melos gen-l10n && melos build_runner